### ISSUE TITLE
Magic Forms events

### ISSUE THREAD

**Issue by skydiver** [therealkevinard/oc-plugin-rwm-mfcontactsview#3]
I've merged your PR (thanks a lot) but i made a single modification:

Instead of:
```
Event::fire('martin.forms.beforeSaveRecord', json_encode($post));
```
this code:
```
Event::fire('martin.forms.beforeSaveRecord', [&$post]);
```

Now we can modify the original form data from plugins before it's saved to database.

These are the modifications on your plugin, Plugin.php, boot method:

```
    public function boot()
    {
        Event::listen('martin.forms.beforeSaveRecord', function (&$formdata) {
            $cnt_params = $formdata;
            $contact = new Contact();
            $contact->name = $cnt_params['name'];
            $contact->email = $cnt_params['email'];
            $contact->subject = $cnt_params['subject'];
            $contact->message = $cnt_params['comments'];
            $contact->save();
            $formdata['name'] = "NEW VALUE";
        });
    }
```

You can test the [BETA branch](https://github.com/skydiver/october-plugin-forms/tree/BETA).

Thanks.-

**Comment by therealkevinard** [comment]
Ah-ah! Much better! That opens up a ton of room for extending. 
Will patch these today (or tomorrow). Thanks!

**Comment by therealkevinard** [comment]
Tested with commit 75e6656df75ff4feb6fcc8b439cdcc249ad5009c 
I made the obvious changes to how the `$formdata` param is handled, and there were no bumps - everything fell immediately into place.

**Comment by skydiver** [comment]
Great.
I'm going to publish new version ... :+1:
